# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"\x9b\x01\n\x0c\x41gentMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12&\n\x07urgency\x18\x03 \x01(\x0e\x32\x15.AgentMessage.Urgency\x12\x13\n\x0b\x61udit_trail\x18\x04 \x03(\t\"1\n\x07Urgency\x12\n\n\x06NORMAL\x10\x00\x12\x0c\n\x08\x45LEVATED\x10\x01\x12\x0c\n\x08\x43RITICAL\x10\x02\x32@\n\x0c\x41gentService\x12\x30\n\x10SendAgentMessage\x12\r.AgentMessage\x1a\r.AgentMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTMESSAGE']._serialized_start=16
  _globals['_AGENTMESSAGE']._serialized_end=171
  _globals['_AGENTMESSAGE_URGENCY']._serialized_start=122
  _globals['_AGENTMESSAGE_URGENCY']._serialized_end=171
  _globals['_AGENTSERVICE']._serialized_start=173
  _globals['_AGENTSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
